package com.jd.jnlu.nlg.model;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class srilmJNI {
  public final static native long initLM(int jarg1);
  public final static native void deleteLM(long jarg1);
  public final static native long getIndexForWord(String jarg1);
  public final static native String getWordForIndex(long jarg1);
  public final static native int readLM(long jarg1, String jarg2);
  public final static native float getWordProb(long jarg1, long jarg2, long jarg3);
  public final static native float getNgramProb(long jarg1, String jarg2, long jarg3);
  public final static native float getUnigramProb(long jarg1, String jarg2);
  public final static native float getBigramProb(long jarg1, String jarg2);
  public final static native float getTrigramProb(long jarg1, String jarg2);
  public final static native float getSentenceProb(long jarg1, String jarg2, long jarg3);
  public final static native float getSentencePpl(long jarg1, String jarg2, long jarg3);
  public final static native int numOOVs(long jarg1, String jarg2, long jarg3);
  public final static native long corpusStats(long jarg1, String jarg2, long jarg3);
  public final static native float getCorpusProb(long jarg1, String jarg2);
  public final static native float getCorpusPpl(long jarg1, String jarg2);
  public final static native int howManyNgrams(long jarg1, long jarg2);
}
